### ISSUE TITLE
Incorrect top naming leads to confusing exception

### ISSUE THREAD

**Issue by jgoeders** [byuccl/bfasst#303]
If you do not have top set correctly (ie there is no <top_name>.v for your given <top_name>), then you get this confusing exception:

```python
Traceback (most recent call last):
  File "/home/jgoeders/bfasst/scripts/run_design.py", line 110, in <module>
    main()
  File "/home/jgoeders/bfasst/scripts/run_design.py", line 106, in main
    run_design(Path(args.design_path), args.flow, args.error_flow, flow_args=flow_args)
  File "/home/jgoeders/bfasst/scripts/run_design.py", line 24, in run_design
    design = Design(design_path, build_dir)
  File "/home/jgoeders/bfasst/bfasst/design.py", line 73, in __init__
    self.process_yaml()
  File "/home/jgoeders/bfasst/bfasst/design.py", line 130, in process_yaml
    self.top_file_path = self.find_top_file()
  File "/home/jgoeders/bfasst/bfasst/design.py", line 167, in find_top_file
    return next(valid_paths)
StopIteration
```

**Comment by KeenanRileyFaulkner** [comment]
Are we looking to maintain run_design/run_experiment stuff? I've kind of been operating towards the end of removing them from the project. I'm happy to investigate this issue if you'd like, though

**Comment by jgoeders** [comment]
No, we aren't going to maintain the old run scripts.
